### ISSUE TITLE
About speed

### ISSUE THREAD

**Issue by Apostatee** [tangsanli5201/DeepPCB#4]
This paper says SSD achieves 64fps with input_size=512, but original paper of SSD only reaches 25fps with input_size=512, Could you please explain it in detail ?

**Comment by tangsanli5201** [comment]
Hi, this is a good question since the efficiency is what we mainly concern for the ONLINE PCB defect detector. There is a mistake in your question that SSD achieves 64fps with input_size=640. (512 is the training size). There are following reasons:
1.  Smaller backbone structure:  VGG-7 is used as the SSD backbone in PCB defect detection task, whose model size is only around 2MB. The original SSD use ResNet50 or more complex backbone structure.
2. The PCB image is in grayscale but the input image for the original SSD is in RGB.
Hope above instructions be useful.

**Comment by Apostatee** [comment]
Thanks tangsanli : )
